apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: rollout-patterns-project
  namespace: argocd
spec:
  description: Project show casing varying rollout patterns
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  sourceRepos:
    - "git@github.com:Oluwatunmise-olat/argocd-k8s-rollout-patterns.git"
  destinations:
    - namespace: default
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc
