apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rolling-update-application
  labels:
    app: rollout-patterns
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: rolling-update-rollout
  template:
    metadata:
      labels:
        app: rolling-update-rollout
    spec:
      containers:
        - name: core
          image: ""
          imagePullPolicy: Always
          ports:
            - containerPort: 3401
          env:
            - name: PORT
              value: "3401"
          livenessProbe:
            httpGet:
              path: /health
              port: 3401
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
